import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Player card demo",
  description: "Generated by create next app",
};

// Runs before paint to avoid a flash of the wrong theme. Reads a saved
// preference if present, otherwise falls back to the OS-level setting.
const themeInitScript = `
(function () {
  try {
    var stored = localStorage.getItem("theme");
    var theme = stored === "dark" || stored === "light"
      ? stored
      : (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
    document.documentElement.setAttribute("data-theme", theme);
  } catch (e) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body>{children}</body>
    </html>
  );
}
